In [185]:
from numpy import array

In [186]:
l = [1.0, 2.0, 3.0, 4.0, 5.0]

In [187]:
type(l)

list

In [188]:
a = array(l)

In [189]:
print(a)

[1. 2. 3. 4. 5.]


In [190]:
type(a)

numpy.ndarray

In [191]:
a.shape

(5,)

In [192]:
print(a.dtype)

float64


In [193]:
from numpy import empty

In [194]:
s = empty([3,3])
print(s)

[[6.95038501e-310 5.02034658e+175 3.12453223e-033]
 [4.27781548e-033 3.06185282e-057 3.56727840e-057]
 [5.01163193e+217 5.49419094e-143 9.80058441e+252]]


In [195]:
from numpy import zeros

In [196]:
a = zeros([3,5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [197]:
from numpy import ones

In [198]:
a = ones([5])
print(a)

[1. 1. 1. 1. 1.]


In [199]:
from numpy import vstack

In [200]:
a1 = array([1,2,3,4])
a2 = array([3,5,7,8])
a3 =array([4,6,8,0])
a4 = vstack((a1,a2,a3))
print(a4)

[[1 2 3 4]
 [3 5 7 8]
 [4 6 8 0]]


In [201]:
from numpy import hstack

In [202]:
b1 = array([1,2,3])
b2 = array([4,5,6])
b3 = hstack((b1, b2))
print(b3)

[1 2 3 4 5 6]


In [203]:
data = array([11,22,33,44,55])
print(data)

[11 22 33 44 55]


In [204]:
print(data.dtype)

int64


In [205]:
print(type(data))

<class 'numpy.ndarray'>


In [206]:
data1 = array([[11,22], [33,44], [55,66]])
print(data1)

[[11 22]
 [33 44]
 [55 66]]


In [207]:
print(type(data1))

<class 'numpy.ndarray'>


In [208]:
print(data[0])

11


In [209]:
print(data[4])

55


In [210]:
for i in data:
    print(i)

11
22
33
44
55


In [211]:
for i in range(len(data)):
    print(i)

0
1
2
3
4


In [212]:
print(data[-1])

55


In [213]:
print(data[-5])

11


In [214]:
data1[0][0]

11

In [215]:
data1[2][1]

66

In [216]:
data[:3]

array([11, 22, 33])

In [217]:
data[:0]

array([], dtype=int64)

In [218]:
data[:-2]

array([11, 22, 33])

In [219]:
data[-2:]

array([44, 55])

In [220]:
x = array([[11,22,33], [44,55,66],[77,88,99]])
print(x)

[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [221]:
x[:, :]

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [ ]:
[row:row, columns:columns]

In [223]:
data.shape

(5,)

In [224]:
data.shape[0]

5

In [225]:
data.reshape(-1,1)

array([[11],
       [22],
       [33],
       [44],
       [55]])

In [226]:
data.reshape(-1,1).shape

(5, 1)

In [227]:
x

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [228]:
x.reshape(1,9)

array([[11, 22, 33, 44, 55, 66, 77, 88, 99]])

In [229]:
x.reshape(9,1)

array([[11],
       [22],
       [33],
       [44],
       [55],
       [66],
       [77],
       [88],
       [99]])

In [230]:
x.reshape(3,3)

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

* L1 norm: sum of the absolute values of the vector, also called taxicab norm or Manhattan norm.
* L2 norm :the square root of the sum of the squared vector value, also called Euclidean norm.
* max norm : the maximum vector values.

In [231]:
from numpy.linalg import norm

In [232]:
a = array([1,2,3])
print(a)

[1 2 3]


In [233]:
l1 = norm(a, 1)
print(l1)

6.0


* L1 norm keep the coefficient of the model small, and in turn less complex.

In [234]:
l2 = norm(a)
print(l2)

3.7416573867739413


* L2 is commonly used than other vector norms.

* Max norm also known as infinity norm

In [235]:
from math import inf

In [236]:
maxnorm = norm(a, inf)
print(maxnorm)

3.0


In [237]:
A = array([[1,2,3], [4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [238]:
B = array([[1,2,3], [4,5,6]])
print(B)

[[1 2 3]
 [4 5 6]]


In [239]:
C = A+B
print(C)

[[ 2  4  6]
 [ 8 10 12]]


In [240]:
C = A*B
print(C)

[[ 1  4  9]
 [16 25 36]]


In [241]:
C = A/B
print(C)

[[1. 1. 1.]
 [1. 1. 1.]]


In [242]:
A = array([[1,2], [3,4], [5,6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [243]:
B = array([[1,2], [3,4]])
print(B)

[[1 2]
 [3 4]]


In [244]:
#dot product
C = A.dot(B)
print(C)

[[ 7 10]
 [15 22]
 [23 34]]


In [245]:
C = A@B
print(C)

[[ 7 10]
 [15 22]
 [23 34]]


In [246]:
from numpy import tril
from numpy import triu

In [247]:
M =  array([[1,2,3],[1,2,3], [1,2,3]])
print(M)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [248]:
lower = tril(M)
print(lower)

[[1 0 0]
 [1 2 0]
 [1 2 3]]


In [249]:
upper = triu(M)
print(upper)

[[1 2 3]
 [0 2 3]
 [0 0 3]]


In [250]:
from numpy import diag

In [251]:
# extract diagonal vector
d = diag(M)
print(d)

[1 2 3]


In [252]:
#create diagonal matrix
D = diag(d)
print(D)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [253]:
from numpy import identity

In [254]:
I = identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [255]:
from numpy.linalg import inv 

In [256]:
Q = array([[1,0],[0,-1]])
print(Q)

[[ 1  0]
 [ 0 -1]]


In [257]:
V = inv(Q)
print(V)

[[ 1.  0.]
 [-0. -1.]]


In [258]:
A = array([[1,2],[3,4],[5,6]])
print(A)
c = A.T

[[1 2]
 [3 4]
 [5 6]]


In [259]:
print(c)

[[1 3 5]
 [2 4 6]]


In [260]:
from numpy.linalg import inv

In [261]:
A = array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [262]:
b = inv(A)
print(b)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [263]:
i = A.dot(b)
print(i)

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


* trace : sum of the values on the main diagonal of the matrix

In [264]:
from numpy import trace

In [265]:
A = array([[1,2,3],[4,5,6],[7,8,9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [266]:
b = trace(A)
b

15

In [267]:
from numpy.linalg import matrix_rank

In [268]:
v1 = array([1,2,3])
print(v1)

[1 2 3]


In [269]:
matrix_rank(v1)

1

In [270]:
from scipy.sparse import csr_matrix

In [271]:
A = array([[1,0,0,1,0,0],[0,0,2,0,0,1],[0,0,0,2,0,0]])
print(A)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


In [272]:
s = csr_matrix(A)
print(s)

  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2


In [273]:
b = s.todense()
print(b)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


In [286]:
T = array([
    [[1,2,3], [4,5,6],[7,8,9]],
    [[11,12,13], [14,15,16], [17,18,19]], 
    [[20,21,22], [23,24,25],[26,27,28]]])

In [287]:
print(T.shape)

(3, 3, 3)


In [288]:
print(T)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[20 21 22]
  [23 24 25]
  [26 27 28]]]


In [289]:
B = array([
    [[1,2,3], [4,5,6],[7,8,9]],
    [[11,12,13], [14,15,16], [17,18,19]], 
    [[20,21,22], [23,24,25],[26,27,28]]])

In [290]:
c = T+B

In [291]:
c

array([[[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]],

       [[22, 24, 26],
        [28, 30, 32],
        [34, 36, 38]],

       [[40, 42, 44],
        [46, 48, 50],
        [52, 54, 56]]])

In [292]:
from numpy import tensordot

In [295]:
a = array([1,2])
b = array([3,4])
c = tensordot(a, b, axes = 0)

In [299]:
print(c)

[[3 4]
 [6 8]]


* L U decomposition is for square matirces, A = L . U
* L is lower triangle matrix and U is the upper triangle matrix

In [300]:
from scipy.linalg import lu

In [302]:
A = array([[1,2,3],
           [4,5,6],
           [7,8,9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [303]:
# factorize
P, L, U = lu(A)

In [304]:
print(P) # p = partial pivoting

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [305]:
print(L)

[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]


In [306]:
print(U)

[[ 7.00000000e+00  8.00000000e+00  9.00000000e+00]
 [ 0.00000000e+00  8.57142857e-01  1.71428571e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.58603289e-16]]


In [307]:
# reconstruct
b = P.dot(L).dot(U)
print(b)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


* QR decomposition is for n * m matrices (not limited to square matrices
* A = Q . R
* Q size m * m, R is an upper triangle matrix with the size m * n

In [308]:
from numpy.linalg import qr

In [309]:
a = array([[1,2], [3,4], [5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [310]:
#factorize
Q, R = qr(a, 'complete')

In [311]:
print(Q)

[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]


In [312]:
print(R)

[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]


In [313]:
# Reconstruct
b = Q.dot(R)
print(b)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


* cholesky decomposition is for square matrices where all values are greater than zeros.
* A = l . L transpose
* L is the lower triangle matrix, L.T is the transpose of L
* used for solving linear least squares for linear regression, as well as simulation and optimization.

In [314]:
from numpy.linalg import cholesky

In [316]:
A = array([[2,1,1],[1,2,1],[1,1,2]])
print(A)

[[2 1 1]
 [1 2 1]
 [1 1 2]]


In [320]:
#factorize
l = cholesky(A)
print(l)

[[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]


In [321]:
# Reconstruct
b = l.dot(l.T)
print(b)

[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]


* Eigendecomopsition decomposing a square matrix into a set of eigenvectors and eigenvalues = 
* eigenvector : A . v = a . v
* A = Q A Q.-1
* Q is a matrix comrised of the eigenvectors, A is the diagonal matrix comprised of the eigenvalues, Q.T is the transpose of the matrix.

* eigenvectors are unit vectors, length or magnitude is equal 1. 
* eigenvalues are coefficients applied to eigenvectors that give the vector their length or magnitude.for example a negative eigenvalue may reverse the direction of the eigenvector as part of scaling it.

In [322]:
from numpy.linalg import eig

In [323]:
A = array([[1,2,3],[4,5,6],[7,8,9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [324]:
#factorize
values, vectors = eig(A)

In [325]:
print(values)

[ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]


In [326]:
print(vectors)

[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [331]:
v_diag = diag(values)
print(v)

[[ 1.61168440e+01  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.11684397e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -9.75918483e-16]]


In [328]:
# to confirm eigenvector is eigenvector : A.v = a . v
_first = A.dot(vectors[:, 0])
print(_first)

[ -3.73863537  -8.46653421 -13.19443305]


In [330]:
c = values[0] * vectors[:,0]
print(c)

[ -3.73863537  -8.46653421 -13.19443305]


In [333]:
# Reconstruct matrix from eigenvectors and eigenvalues
inv_eig = inv(vectors)
print(inv_eig)

[[-0.48295226 -0.59340999 -0.70386772]
 [-0.91788599 -0.24901003  0.41986593]
 [ 0.40824829 -0.81649658  0.40824829]]


In [334]:
B = vectors.dot(v_diag).dot(inv_eig)
print(B)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


* Singular Value Decomposition: area of applications, compressing, denoising, and data reduction.
* A = U . segma . V.T   
* A is real n * m matrix, U is n * n matrix, sigma is n * m diagonal matrix, V.T is the V transpose of m * m matrix.
* SVD can be used in least squares linear regression, image compression, denoising data.

In [336]:
from scipy.linalg import svd

In [337]:
A = array([
    [1,2],
    [3,4],
    [5,6]])
print(A) # A: n*m

[[1 2]
 [3 4]
 [5 6]]


In [339]:
# factorize
U, S, V = svd(A)
print(U)

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]


In [340]:
print(S)

[9.52551809 0.51430058]


In [341]:
print(V)

[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [342]:
from numpy import zeros

In [350]:
#create m*n Sigma matrix
sigma = zeros((A.shape[0], A.shape[1]))
print(sigma)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [351]:
# populate Sigma with n*n diagonal matrix
sigma[:A.shape[1], :A.shape[1]] = diag(S)

In [352]:
print(sigma)

[[9.52551809 0.        ]
 [0.         0.51430058]
 [0.         0.        ]]


In [354]:
# Reconstruct matrix
B = U.dot(sigma.dot(V))
print(B)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


* Pseudoinverse also Moore-Penrose : generalizatio of the matrix inverse for square matrices to rectangular matrices.


In [355]:
from numpy.linalg import pinv

In [361]:
A = array([
    [0.1, 0.2],
    [0.3, 0.4],
    [0.5, 0.6],
    [0.7, 0.8]])
print(A)

[[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]
 [0.7 0.8]]


In [362]:
B = pinv(A)
print(B)

[[-1.00000000e+01 -5.00000000e+00  9.07607323e-15  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]


In [363]:
#calculat SVD
U, s, V= svd(A)

In [368]:
d = 1.0 / s
d

array([ 0.70081527, 15.95333376])

In [371]:
#create m*n matrix
D = zeros(A.shape)
print(D)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [374]:
#populate D with n*n
D[:A.shape[1],:A.shape[1]]= diag(d)
print(D)

[[ 0.70081527  0.        ]
 [ 0.         15.95333376]
 [ 0.          0.        ]
 [ 0.          0.        ]]


In [375]:
B = V.T.dot(D.T).dot(U.T)
print(B)

[[-1.00000000e+01 -5.00000000e+00  9.07607323e-15  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]


* Dimensionality Reduction

In [376]:
A = array([
    [1,2,3,4,5,6,7,8,9,10],
    [11,12,13,14,15,16,17,18,19,20],
    [21,22,23,24,25,26,27,28,29,30]
])
print(A)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


In [395]:
#factoeize
U, s, V = svd(A)

In [396]:
V.shape

(10, 10)

In [397]:
sigma = zeros(A.shape)
print(sigma)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [398]:
s

array([9.69657342e+01, 7.25578339e+00, 5.82172067e-15])

In [399]:
sigma[:A.shape[0], :A.shape[0]] = diag(s)
print(sigma)

[[9.69657342e+01 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 7.25578339e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 5.82172067e-15 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]]


In [400]:
n_elements = 2
sigma = sigma[:, :n_elements]
sigma

array([[96.96573419,  0.        ],
       [ 0.        ,  7.25578339],
       [ 0.        ,  0.        ]])

In [404]:
V = V[:n_elements, :]
V

array([[-0.24139304, -0.25728686, -0.27318068, -0.2890745 , -0.30496832,
        -0.32086214, -0.33675595, -0.35264977, -0.36854359, -0.38443741],
       [-0.53589546, -0.42695236, -0.31800926, -0.20906617, -0.10012307,
         0.00882003,  0.11776313,  0.22670623,  0.33564933,  0.44459242]])

In [402]:
f = U.dot(sigma.dot(V))
f

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25., 26., 27., 28., 29., 30.]])

In [403]:
# transform
T = U.dot(sigma)
T

array([[-18.52157747,   6.47697214],
       [-49.81310011,   1.91182038],
       [-81.10462276,  -2.65333138]])

In [406]:
T = A.dot(V.T)
T

array([[-18.52157747,   6.47697214],
       [-49.81310011,   1.91182038],
       [-81.10462276,  -2.65333138]])